config/routes.rb
Rails.application.routes.draw do
  # root :to => "home#index"
   root :to => "users#new"

  # 新規登録画面のルート
  resource :users, only: [:new, :show, :edit, :create, :update]

  # ログイン時のパスを取得
  get 'login', to: 'sessions#new', as: 'new_sessions' # ログイン前の処理
  post 'login', to: 'sessions#create', as: 'create_sessions' # ログイン後の処理
  delete 'logout', to: 'sessions#destroy', as: 'destroy_sessions' # ログアウト処置

  # ログイン後のパスを取得
  get "home/index"
  get "home/explore"
  get "home/messages"
  get "home/notifications"
  get "home/message_post", as: "message_post"
  get "home/profile"

  # ツイート表示のパス
  post "home" => "home#create"

  # ツイートの削除
  delete "home/:id" => "home#destroy", as: "tweet_destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: {minimum:2, maximum:16}
    validates :s_number, presence: true, uniqueness: true
    validates :password, presence: true, format: {with: /\A[0-9]+\z/, multiline: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :current_user
    # ツイート内容の表示（全体）
    def index
        @tweet = Tweet.new
        @tweets = Tweet.all.order(created_at: :desc)
    end
    def profile
        @tweet = Tweet.new
        @tweets = Tweet.all.order(created_at: :desc)
        # Userのs_numberを参照し、それに対応するTweet.user_numberをカウント
        tweet_count = Tweet.where(user_number: @user.s_number).order(created_at: :desc)
        @tweet_count = tweet_count.count
    end

    # ツイート
    def explore
        @tweet = Tweet.new
    end
    def notifications
        @tweet = Tweet.new
    end
    def messages
        @tweet = Tweet.new
    end

    # ツイート内容を保存
    def create
        tweet = Tweet.new(tweet_params)
        tweet.save
        flash[:notice] = "投稿しました"
        redirect_to home_index_path
    end

    def destroy
        @tweet_destroy = Tweet.find(params[:id])
        if @tweet_destroy.destroy
          flash[:notice] = "投稿を削除しました"
          redirect_to home_index_path
        else
          flash.now[:alert] = "削除に失敗しました"
          render action: "new"
        end
    end

    private

    def current_user
        if session[:user_id]
            @user = User.find(session[:user_id])
        else
            redirect_to new_sessions_path
        end
    end

    def tweet_params
        params.require(:tweet).permit(:user_name, :user_number, :t_time, :content, :comment, :diffusion, :like)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in?, only: [:new, :create]

    def new

    end

    def create
        @user = User.find_by(s_number: params[:s_number], password: params[:password])
        if @user
            session[:user_id] = @user.id
            flash[:notice] = "ログインに成功しました。"
            redirect_to home_index_path
        else
            flash.now[:alert] = "パスワードが間違っているか、存在しないユーザーです"
            render action: "new"
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "ログアウトしました。"
        redirect_to new_sessions_path
    end

    private
    def logged_in?
        if session[:user_id]
            @user = User.find(session[:user_id])
            redirect_to home_index_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user_new = User.new
    end

    def show

    end

    def edit

    end

    def create
        @user_new = User.new(user_params)

        if @user_new.save
            session[:user_id] = @user_new.id
            flash[:notice] = "アカウントを作成しました。"
            redirect_to home_index_path
        else
            flash.now[:alert] = "アカウント作成に失敗しました。"
            render action: "new"
        end
    end

    def update

    end

    private
    
    def user_params
        params.require(:user).permit(:name, :s_number, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def distance_in_words_japanese(days)
        if days <= 7
          I18n.t('datetime.distance_in_words.x_days', count: days)
        else
          years = days / 365
          months = (days % 365) / 30
          remaining_days = days % 30
          I18n.t('datetime.distance_in_words.x_days_over_7', years: years, months: months, days: remaining_days)
        end
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/explore.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>Twitter Clone</title>
</head>
<body>
    <header class="sidebar">
        <%= link_to image_tag("/assets/starlin _logo.png", class: "home_logo"), "index" %>
        
        <%= link_to "index" do%>
            <img src="/assets/home/home.png"><p>Home</p>
        <% end %>
        <%= link_to "explore" do %>
            <img src="/assets/home/explore.png"><p>Explore</p>
        <% end %>
        <%= link_to "notifications" do %>
            <img src="/assets/home/notifications.png"><p>Notifications</p>
        <% end %>
        <%= link_to "messages" do %>
            <img src="/assets/home/message.png"><p>Messages</p>
        <% end %>
        <%= link_to "profile" do %>
            <img src="/assets/home/pofile.png"><p>Profile</p>
        <% end %>
        
        <a href="#" class="postbtn" id="openModalpostBtn" >Post</a>

        <% if @user.nil? %>
            <%= link_to "Login", new_sessions_path, method: :get %>
        <% else %>
            <%# ログインユーザー名表示 %>
            <div class="accountbar">
                <a href="#" id="openModalbarBtn">
                    <img src="/assets/home/icon.jpg">
                    <p class="namead"><%= @user.name %></p>
                    <img src="/assets/home/tententen.png" class="tententen">
                </a>
            </div>
            <%# ログアウトボタン %>
            <div class="bar" id="barModal">
                <div class="modal-content4">
                    <%= button_to "Logout", destroy_sessions_path,  method: :delete, class: "logout" %>
                </div>
            </div>
        <% end %>
    </header>

    <main class="content">
        <h1>Explore</h1>
        <%#ツイート（投稿）機能 %>
        <div class="post" id="postModal">
            <div class="modal-content3">
                <span class="close3">&times;</span>
                <img src="/assets/home/icon.jpg">
                <%= form_for(@tweet, url: "/home") do |f| %>
                    <%= f.hidden_field :user_name, value: @user.name %>
                    <%= f.hidden_field :user_number, value: @user.s_number %>
                    <%# ツイートの書き込み %>
                    <%= f.text_area :content, rows: 7, placeholder: "What's happening?!", class: "message_content" %>
                    <%= f.hidden_field :comment, value: nil %>
                    <%= f.hidden_field :diffusion, value: nil %>
                    <%= f.hidden_field :like, value: nil %>
                    <%= f.submit "Post", class: "btn" %>
                    <%# 削除ボタン %>
                <% end %>
            </div>
        </div>
    </main>
    
    <footer class="search">
        <div class="header">              
            <p><%= text_field_tag :search, nil, placeholder: "Search..." %></p>
            <%= button_tag 'Search', type: 'submit', class: "searchbtn" %>
        </div>
    </footer>

    <script>
        /*アカウントバー*/
        const bar = document.getElementById('barModal');
        const openModalbarBtn = document.getElementById('openModalbarBtn');

        openModalbarBtn.onclick = function() {
            // モーダルが表示されているかどうかを切り替える
            if (bar.style.display === 'block') {
                bar.style.display = 'none'; // モーダルを非表示
            } else {
                bar.style.display = 'block'; // モーダルを表示
            }
        }

        /*ポスト*/
        const tweet = document.getElementById('postModal');
        const openModalpostBtn = document.getElementById('openModalpostBtn');
        const closeBtn3 = document.getElementsByClassName('close3')[0];
        /* スクロールの禁止 */
        const body = document.getElementsByTagName('body')[0]; // body要素を取得

        openModalpostBtn.onclick = function() {
            tweet.style.display = 'block';
            body.classList.add('no_scroll'); // スクロール禁止
        }

        closeBtn3.onclick = function() {
            tweet.style.display = 'none';
            body.classList.remove('no_scroll'); // スクロール許可
        }

        window.onclick = function(event) {
            if (event.target == tweet) {
                tweet.style.display = 'none';
                body.classList.remove('no_scroll'); // スクロール許可
            }
        }
    </script>
</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>Twitter Clone</title>
</head>
<body>
    <header class="sidebar">
        <%= link_to image_tag("/assets/starlin _logo.png", class: "home_logo"), "index" %>
        
        <%= link_to "index" do%>
            <img src="/assets/home/home.png"><p>Home</p>
        <% end %>
        <%= link_to "explore" do %>
            <img src="/assets/home/explore.png"><p>Explore</p>
        <% end %>
        <%= link_to "notifications" do %>
            <img src="/assets/home/notifications.png"><p>Notifications</p>
        <% end %>
        <%= link_to "messages" do %>
            <img src="/assets/home/message.png"><p>Messages</p>
        <% end %>
        <%= link_to "profile" do %>
            <img src="/assets/home/pofile.png"><p>Profile</p>
        <% end %>
        
        <a href="#" class="postbtn" id="openModalpostBtn" >Post</a>

        <% if @user.nil? %>
            <%= link_to "Login", new_sessions_path, method: :get %>
        <% else %>
            <%# ログインユーザー名表示 %>
            <div class="accountbar">
                <a href="#" id="openModalbarBtn">
                    <img src="/assets/home/icon.jpg">
                    <p class="namead"><%= @user.name %></p>
                    <img src="/assets/home/tententen.png" class="tententen">
                </a>  
            </div>
            <%# ログアウトボタン %>
            <div class="bar" id="barModal">
                <div class="modal-content4">
                    <%= button_to "Logout", destroy_sessions_path,  method: :delete, class: "logout" %>
                </div>
            </div>
        <% end %>
    </header>

    <main class="content">
        <%#ツイート（投稿）機能 %>
        <div class="post" id="postModal">
            <div class="modal-content3">
                <span class="close3">&times;</span>
                <img src="/assets/home/icon.jpg">
                <%= form_for(@tweet, url: "/home") do |f| %>
                    <%= f.hidden_field :user_name, value: @user.name %>
                    <%= f.hidden_field :user_number, value: @user.s_number %>
                    <%# ツイートの書き込み %>
                    <%= f.text_area :content, rows: 7, placeholder: "What's happening?!", class: "message_content" %>
                    <%= f.hidden_field :comment, value: nil %>
                    <%= f.hidden_field :diffusion, value: nil %>
                    <%= f.hidden_field :like, value: nil %>
                    <%= f.submit "Post", class: "btn" %>
                <% end %>
            </div>
        </div>
        
        <%# ツイート内容の表示 %>
        <div class="display_slct">
            <%# 全体の投稿 %>
            <label>
                <input type="radio" name="tab" checked>
                For you
            </label>
            <div class="tweet_area">
                <% @tweets.each do |tweet| %>
                    <div class="tweet">
                        <img src="/assets/home/icon.jpg" class="icon">
                        <h3><%= tweet.user_name %></h3>
                        <p class="tweet_id">@<%= tweet.user_number %></p>
                        <p class="tweet_time"><%= "#{time_ago_in_words(tweet.created_at)}前" %></p>
                        <%# 削除ボタン %>
                        <% if @user.s_number == tweet.user_number %>
                            <%= button_to tweet_destroy_path(tweet.id), method: :delete, class: "destroy_btn" do %>
                                <%= image_tag("/assets/home/delete.png", alt: "削除") %>
                            <% end %>
                        <% else %>
                            <%= button_to "", class: "menu_btn" do %>
                                <%= image_tag("/assets/home/tententen.png", alt: "投稿メニュー") %>
                            <% end %>
                        <% end %>
                    </div>
                    <%# 投稿表示 %>
                    <p class="tweet_content"><%= tweet.content %></p>
                    <%# 返信やいいねなど %>
                    <div class="good">
                        <%= button_to "" do %>
                            <%= image_tag("/assets/home/post.png", alt: "返信") %>
                        <% end %>
                        <% if tweet.like == nil %>
                            <p></p>
                        <% elsif tweet.like <= 1 %>
                            <p>0</p>
                        <% end %>
                        <%= button_to "" do %>
                            <%= image_tag("/assets/home/RT.png", alt: "RT") %>
                        <% end %>
                        <% if tweet.like == nil %>
                            <p></p>
                        <% elsif tweet.like <= 1 %>
                            <p>0</p>
                        <% end %>
                        <%= button_to "" do %>
                            <%= image_tag("/assets/home/good.png", alt: "いいね") %>
                        <% end %>
                        <% if tweet.like == nil %>
                            <p></p>
                        <% elsif tweet.like <= 1 %>
                            <p>0</p>
                        <% end %>
                    </div>
                <% end %>
            </div>
            <%# フォローメンバーの投稿 %>
            <label>
                <input type="radio" name="tab">
                Following
            </label>
    </main>

    <footer class="search">
        <div class="header">              
            <p><%= text_field_tag :search, nil, placeholder: "Search..." %></p>
            <%= button_tag 'Search', type: 'submit', class: "searchbtn" %>
        </div>
    </footer>

    <script>
        /*アカウントバー*/
        const bar = document.getElementById('barModal');
        const openModalbarBtn = document.getElementById('openModalbarBtn');

        openModalbarBtn.onclick = function() {
            // モーダルが表示されているかどうかを切り替える
            if (bar.style.display === 'block') {
                bar.style.display = 'none'; // モーダルを非表示
            } else {
                bar.style.display = 'block'; // モーダルを表示
            }
        }

        /*ポスト*/
        const tweet = document.getElementById('postModal');
        const openModalpostBtn = document.getElementById('openModalpostBtn');
        const closeBtn3 = document.getElementsByClassName('close3')[0];
        /* スクロールの禁止 */
        const body = document.getElementsByTagName('body')[0]; // body要素を取得

        openModalpostBtn.onclick = function() {
            tweet.style.display = 'block';
            body.classList.add('no_scroll'); // スクロール禁止
        }

        closeBtn3.onclick = function() {
            tweet.style.display = 'none';
            body.classList.remove('no_scroll'); // スクロール許可
        }

        window.onclick = function(event) {
            if (event.target == tweet) {
                tweet.style.display = 'none';
                body.classList.remove('no_scroll'); // スクロール許可
            }
        }
    </script>
</body>
</html>

app/views/home/message_post.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="styles.css">
    <title>Twitter Clone</title>
</head>
<body>
    <header class="sidebar">
        <%= link_to image_tag("/assets/starlin _logo.png", class: "home_logo"), "index" %>
        
        <div>
            <p><img src="/assets/home/home.png"></p>
            <%= link_to "Home", "index"%>
        </div>
        <div>
            <p><img src="/assets/home/explore.png"></p>
            <%= link_to 'Explore', "explore" %>
        </div>
        <div>
            <p><img src="/assets/home/notifications.png"></p>
            <%= link_to 'Notifications', "notifications" %>
        </div>
        <div>
            <p><img src="/assets/home/message.png"></p>
            <%= link_to 'Messages', "messages" %>
        </div>
        <div>
            <p><img src="/assets/home/pofile.png"></p>
            <%= link_to 'Profile', "profile" %>
        </div>
        
        <a href="#" class="postbtn" id="openModalpostBtn" >Post</a>

        <% if @user.nil? %>
            <%= link_to "Login", new_sessions_path, method: :get %>
        <% else %>
            <%# ログインユーザー名表示 %>
            <div class="accountbar">
                <a href="#" id="openModalbarBtn">
                    <img src="/assets/home/icon.jpg">
                    <p class="namead"><%= @user.name %></p>
                    <img src="/assets/home/tententen.png" class="tententen">
                </a>
            </div>
            <%# ログアウトボタン %>
            <div class="bar" id="barModal">
                <div class="modal-content4">
                    <%= button_to "Logout", destroy_sessions_path,  method: :delete, class: "logout" %>
                </div>
            </div>
        <% end %>
    </header>

    <main class="content">
        <div>
            <h1>Explore</h1>
            <%#ツイート（投稿）機能 %>
            <div class="post" id="postModal">
                <div class="modal-content3">
                    <span class="close3">&times;</span>
                    <img src="/assets/home/icon.jpg">
                    <%= form_for(@tweet, url: "/home") do |f| %>
                        <%= f.hidden_field :user_name, value: @user.name %>
                        <%= f.hidden_field :user_number, value: @user.s_number %>
                        <%# ツイートの書き込み %>
                        <%= f.text_area :content, rows: 7, placeholder: "What's happening?!", class: "message_content" %>
                        <%= f.hidden_field :comment, value: nil %>
                        <%= f.hidden_field :diffusion, value: nil %>
                        <%= f.hidden_field :like, value: nil %>
                        <%= f.submit "Post", class: "btn" %>
                    <% end %>
                </div>
            </div>
        </div>


    </main>
    <footer class="search">
        <div class="header">
            <p><%= text_field_tag :search, nil, placeholder: "Search..." %></p>
            <%= button_tag 'Search', type: 'submit', class: "searchbtn" %>
        </div>
    </footer>

    <script>
        /*ポスト*/
        const tweet = document.getElementById('postModal');
        const openModalpostBtn = document.getElementById('openModalpostBtn');
        const closeBtn3 = document.getElementsByClassName('close3')[0];

        openModalpostBtn.onclick = function() {
            tweet.style.display = 'block';
        }

        closeBtn3.onclick = function() {
            tweet.style.display = 'none';
        }

        window.onclick = function(event) {
            if (event.target == tweet) {
                post.style.display = 'none';
            }
        }
        /*アカウントバー*/
        const bar = document.getElementById('barModal');
        const openModalbarBtn = document.getElementById('openModalbarBtn');

        openModalbarBtn.onclick = function() {
            // モーダルが表示されているかどうかを切り替える
            if (bar.style.display === 'block') {
                bar.style.display = 'none'; // モーダルを非表示
            } else {
                bar.style.display = 'block'; // モーダルを表示
            }
        }
    </script>
</body>
</html>

app/views/home/profile.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>Twitter Clone</title>
</head>
<body>
    <header class="sidebar">
        <%= link_to image_tag("/assets/starlin _logo.png", class: "home_logo"), "index" %>
        
        <%= link_to "index" do%>
            <img src="/assets/home/home.png"><p>Home</p>
        <% end %>
        <%= link_to "explore" do %>
            <img src="/assets/home/explore.png"><p>Explore</p>
        <% end %>
        <%= link_to "notifications" do %>
            <img src="/assets/home/notifications.png"><p>Notifications</p>
        <% end %>
        <%= link_to "messages" do %>
            <img src="/assets/home/message.png"><p>Messages</p>
        <% end %>
        <%= link_to "profile" do %>
            <img src="/assets/home/pofile.png"><p>Profile</p>
        <% end %>
        
        <a href="#" class="postbtn" id="openModalpostBtn" >Post</a>

        <% if @user.nil? %>
            <%= link_to "Login", new_sessions_path, method: :get %>
        <% else %>
            <%# ログインユーザー名表示 %>
            <div class="accountbar">
                <a href="#" id="openModalbarBtn">
                    <img src="/assets/home/icon.jpg">
                    <p class="namead"><%= @user.name %></p>
                    <img src="/assets/home/tententen.png" class="tententen">
                </a>
            </div>
            <%# ログアウトボタン %>
            <div class="bar" id="barModal">
                <div class="modal-content4">
                    <%= button_to "Logout", destroy_sessions_path,  method: :delete, class: "logout" %>
                </div>
            </div>
        <% end %>
    </header>

    <main class="prof_content">
        <!-- プロフィール設定 -->
        <div class="profile_edit" id="EditModel">
            <div class="modal-content5">
                <span class="close4">&times;</span>
                <div>
                    <h1>Edit profile</h1>
                    <%= button_tag("Save", type:"submit") %>
                </div>
                <div>
                    <%= image_tag("/assets/home/hedder.jpg", alt: "editHeader") %>
                </div>
                <div>
                    <div>
                        <%= image_tag("/assets/home/edita_camera.png", alt: "editCamera") %>
                    </div>
                    <div>
                        <%= image_tag("/assets/home/exit.png", alt: "exit") %>
                    </div>
                </div>
                <div>
                    <%= image_tag("/assets/home/icon.jpg", alt: "profileEdit") %>
                    <div>
                        <%= image_tag("/assets/home/edita_camera.png", alt: "editCamera") %>
                    </div>
                </div>
                <div>
                    <p>Name</p>
                    <%= text_field_tag("", @user.name, class: "name") %>
                </div>
                <div>
                    <p>Bio</p>
                    <%= text_area_tag("", "コメントコメントコメントコメントコメントコメントコメントコメントコメントコメントコメントコメント", class: "Bio") %>
                </div>
                <div>
                    <p>Location</p>
                    <%= text_field_tag("", "Jr2353.new", class: "Location") %>
                </div>
                <div>
                    <p>生年月日・</p>
                    <a href="#">Edit</a>
                </div>
                    <h2>1999/11/18</h2>
            </div>
        </div>
        <%# プロフ表示 %>
        <div class="profile_header">
            <%= link_to image_tag("/assets/home/buck.png", alt: "戻る"),  'javascript:history.back()' %>
            <div>
            <h1><%= @user.name %></h1>
                <div>
                    <p><%= @tweet_count %></p><p>posts</p>
                </div>
            </div>
        </div>
        <div class="profile_body">
            <div>
                <div>
                    <%= image_tag("/assets/home/hedder.jpg", alt: "ProfileHeader") %>
                </div>
                <div>
                    <%= image_tag("/assets/home/icon.jpg", alt: "ProfileImg") %>
                </div>
            </div>
            <a href="#" class="editBtn" id="openModalEditBtn" >Edit profile</a>
        </div>
            <h2 class="profile_name"><%= @user.name %></h2>
            <p class="profile_status">@<%= @user.s_number %></p>
            <p class="profile_comment">コメントコメントコメントコメントコメントコメントコメントコメントコメントコメントコメントコメント</p>
            <p class="profile_status"><%= @user.created_at.strftime('%Y年%-m月から坪ッターを利用しています') %></p>
            <div class="follo">
                <p>0</p><p>Following</p>
                <p>0</p><p>Followers</p>
            </div>
        <%# 投稿表示 %>
        <div class="tab">
            <label>
                <input type="radio" name="tab" checked>
                post
            </label>
            <div class="tweet_area">
                <% @tweets.each do |tweet| %>
                    <% if @user.s_number == tweet.user_number %>
                        <div class="tweet">
                            <img src="/assets/home/icon.jpg" class="icon">
                            <h3><%= tweet.user_name %></h3>
                            <p class="tweet_id">@<%= tweet.user_number %></p>
                            <p class="tweet_time"><%= "#{time_ago_in_words(tweet.created_at)}前" %></p>
                            <%# 削除ボタン %>
                            <%= button_to tweet_destroy_path(tweet.id), method: :delete, class: "destroy_btn" do %>
                                <%= image_tag("/assets/home/delete.png", alt: "削除") %>
                            <% end %>
                        </div>
                        <%# 投稿表示 %>
                        <p class="tweet_content"><%= tweet.content %></p>
                        <%# 返信やいいねなど %>
                        <div class="good">
                            <%= button_to "" do %>
                                <%= image_tag("/assets/home/post.png", alt: "返信") %>
                            <% end %>
                        <% if tweet.like == nil %>
                            <p></p>
                        <% elsif tweet.like <= 1 %>
                            <p>0</p>
                        <% end %>
                            <%= button_to "" do %>
                                <%= image_tag("/assets/home/RT.png", alt: "RT") %>
                            <% end %>
                        <% if tweet.like == nil %>
                            <p></p>
                        <% elsif tweet.like <= 1 %>
                            <p>0</p>
                        <% end %>
                            <%= button_to "" do %>
                                <%= image_tag("/assets/home/good.png", alt: "いいね") %>
                            <% end %>
                        <% if tweet.like == nil %>
                            <p></p>
                        <% elsif tweet.like <= 1 %>
                            <p>0</p>
                        <% end %>
                        </div>
                    <% end %>
                <% end %>
            </div>

            <label>
                <input type="radio" name="tab">
                media
            </label>
            <div>メディア</div>

            <label>
                <input type="radio" name="tab">
                good
            </label>
            <div>いいね</div>
        </div>
        <%#ツイート（投稿）機能 %>
        <div class="post" id="postModal">
            <div class="modal-content3">
                <span class="close3">&times;</span>
                <img src="/assets/home/icon.jpg">
                <%= form_for(@tweet, url: "/home") do |f| %>
                    <%= f.hidden_field :user_name, value: @user.name %>
                    <%= f.hidden_field :user_number, value: @user.s_number %>
                    <%# ツイートの書き込み %>
                    <%= f.text_area :content, rows: 7, placeholder: "What's happening?!", class: "message_content" %>
                    <%= f.hidden_field :comment, value: nil %>
                    <%= f.hidden_field :diffusion, value: nil %>
                    <%= f.hidden_field :like, value: nil %>
                    <%= f.submit "Post", class: "btn" %>
                <% end %>
            </div>
        </div>
    </main>

    <footer class="search">
        <div class="header">
            <p><%= text_field_tag :search, nil, placeholder: "Search..." %></p>
            <%= button_tag 'Search', type: 'submit', class: "searchbtn" %>
        </div>
    </footer>

    <script>
        /*ログアウトボタン*/
        const bar = document.getElementById('barModal');
        const openModalbarBtn = document.getElementById('openModalbarBtn');

        openModalbarBtn.onclick = function() {
            // モーダルが表示されているかどうかを切り替える
            if (bar.style.display === 'block') {
                bar.style.display = 'none'; // モーダルを非表示
            } else {
                bar.style.display = 'block'; // モーダルを表示
            }
        }

        /*ポスト*/
        const tweet = document.getElementById('postModal');
        const openModalpostBtn = document.getElementById('openModalpostBtn');
        const closeBtn3 = document.getElementsByClassName('close3')[0];
        /* スクロールの禁止 */
        const body = document.getElementsByTagName('body')[0]; // body要素を取得

        openModalpostBtn.onclick = function() {
            tweet.style.display = 'block';
            body.classList.add('no_scroll'); // スクロール禁止
        }

        closeBtn3.onclick = function() {
            tweet.style.display = 'none';
            body.classList.remove('no_scroll'); // スクロール許可
        }

        window.onclick = function(event) {
            if (event.target == tweet) {
                tweet.style.display = 'none';
                body.classList.remove('no_scroll'); // スクロール許可
            }
        }

        /*プロフィール設定*/
        const edit = document.getElementById('EditModel');
        const openModalEditBtn = document.getElementById('openModalEditBtn');
        const editClose = document.getElementsByClassName('close4')[0];

        openModalEditBtn.onclick = function() {
            edit.style.display = 'block';
            body.classList.add('no_scroll'); // スクロール禁止
        }

        editClose.onclick = function() {
            edit.style.display = 'none';
            body.classList.remove('no_scroll'); // スクロール許可
        }

        window.onclick = function(event) {
            if (event.target == edit) {
                edit.style.display = 'none';
                body.classList.remove('no_scroll'); // スクロール許可
            }
        }
    </script>
</body>
</html>